[pytest]
addopts = -v -s --html=reports/report.html --self-contained-html
markers =
    smoke: Quick high priority smoke tests
    regression: Full regression tests
    sanity: Basic checks
    critical: Critical functional tests
    integration: API or service integration tests